services:
  discord-bot:
    build: .
    container_name: meoxp-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4444:80"
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      meoxp-network:
        ipv4_address: 172.28.0.3

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"
    networks:
      meoxp-network:
        ipv4_address: 172.28.0.2

networks:
  meoxp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
